server:
  port: 8001


logging:
  level:
    com:
      ylz:
        mapper: debug
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
  instance:
    instance-id: cloud-payment-service8001
    prefer-ip-address: true
spring:
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      probability: 0.5
