server:
  port: 80

spring:
  application:
    name: cloud-payment-consumer

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7001/eureka/
  instance:
    instance-id: cloud-payment-consumer
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      probability: 0.5