server:
  port: 82
spring:
  cloud:
    consul:
      host: 192.168.189.132
      port: 8500
      discovery:
        service-name: ${spring.application.name}
  application:
    name: cloud-consumer-payment-consul

