spring:
  application:
    name: cloud-stream-provider
  cloud:
    stream:
      binders:
        defaultRabbit:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: 192.168.189.133
      bindings:
        input: #跟实现类中的MessageChannel实体名称相同
          destination: studyExchange #订阅主题的名称
          content-type: application/json
          binder: defaultRabbit
         # group: test   #配置后自动支持消息持久化和分组避免重复消费
server:
  port: 5004
